name: Static Checks
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  misspell:
    concurrency:
      group: ${{ github.ref }}-misspell-lint
      cancel-in-progress: true
    name: Check spelling using misspell
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@v3

      - name: misspell
        id: check_for_typos
        uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "./documentation"
          locale: "US"
          level: "warning"
          pattern: |
            *.md
            *.mdx
