name: e2e tests

on: [pull_request]

jobs:
  generate_e2e_projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kanga333/json-array-builder@main
        id: array
        with:
          cmd: ls e2e
          separator: newline
    outputs:
      param: ${{ steps.array.outputs.build }}
  cypress-e2e-tests:
    needs:
      - generate_e2e_projects
    strategy:
      matrix:
        projectName: ${{ fromJson(needs.generate_e2e_projects.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy e2e files
        run: |
          cp -R ./e2e/${{ matrix.projectName }}/. ./examples/${{ matrix.projectName }}
      - uses: actions/checkout@v3
      - name: Install & Build Deps
        run: |
          cd examples/${{ matrix.projectName }}
          npm install
          npm run build
          npm run start &
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          command: npx cypress run --project ./examples/${{ matrix.projectName }} --record --group react --parallel --ci-build-id refine-${{ matrix.projectName }}-${{ github.run_attempt }}
          install: false
          wait-on: "http://localhost:5173"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
