name: e2e tests

on: [pull_request]

jobs:
  find-cypress-config:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kanga333/json-array-builder@main
        id: array
        with:
          cmd: find . -name cypress.config.ts
          separator: newline
    outputs:
      param: ${{ steps.array.outputs.build }}
  run-cypress-tests:
    needs:
      - find-cypress-config
    strategy:
      matrix:
        cypressConfig: ${{ fromJson(needs.find-cypress-config.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install & Build Deps
        run: |
          examplePath=$(echo "${{ matrix.cypressConfig }}" | sed 's/\/cypress.config.ts//g')
          cd $examplePath
          npm install
          npm run start -- --host 127.0.0.1 &
      # - name: Run Cypress
      #   run: |
      #     examplePath=$(echo "${{ matrix.cypressConfig }}" | sed 's/\/cypress.config.ts//g')
      #     cd $examplePath
      #     npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} -C ${{ matrix.cypressConfig }} --parallel --ci-build-id refine-${{ matrix.projectName }}-${{ github.run_attempt }}
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          install: false
          command: pwd && npx cypress run --record -C ./cypress.config.ts --parallel --ci-build-id refine-${{ matrix.cypressConfig }}-${{ github.run_attempt }}
          # start: "npm ls"
          wait-on: "http://127.0.0.1:5773"
          project: ./examples/base-antd
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
