name: e2e tests

on: [pull_request]

jobs:
  generate_e2e_projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kanga333/json-array-builder@main
        id: array
        with:
          cmd: ls e2e
          separator: newline
    outputs:
      param: ${{ steps.array.outputs.build }}
  cypress-e2e-tests:
    needs:
      - generate_e2e_projects
    strategy:
      matrix:
        projectName: ${{ fromJson(needs.generate_e2e_projects.outputs.param) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy e2e files
        run: |
          cp -R ./e2e/${{ matrix.projectName }}/. ./examples/${{ matrix.projectName }}
      - uses: actions/checkout@v3
      - name: Install & Build Deps
        run: |
          cd examples/${{ matrix.projectName }}
          npm install
          npm run build
          npm run start -- --host 127.0.0.1 &
      - name: Run Cypresss
        run: |
          cd ../../
          npx cypress run --key ${{ secrets.CYPRESS_RECORD_KEY }} --project ./examples/${{ matrix.projectName }} --record --parallel --ci-build-id refine-${{ matrix.projectName }}-${{ github.run_attempt }}
