name: Deploy Example Previews

on:
  push:
    paths:
      - "packages/**"
      - "examples/finefoods-antd/**"
      - "examples/finefoods-client/**"
      - "examples/finefoods-material-ui/**"
      - "examples/app-crm/**"
      - "examples/pixels/**"
      - "examples/invoicer/**"
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      examples: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          'finefoods-antd': 'examples/finefoods-antd/**'
          'finefoods-client': 'examples/finefoods-client/**'
          'finefoods-material-ui': 'examples/finefoods-material-ui/**'
          'app-crm': 'examples/app-crm/**'
          'pixels': 'examples/pixels/**'
          'invoicer': 'examples/invoicer/**'

  deploy_example_preview:
    needs: changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    strategy:
      matrix:
        example: ${{ fromJson(needs.changes.outputs.examples) }}
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install Dependencies
        run: pnpm install --ignore-scripts
      - name: Build example
        run: pnpm build --scope ${{ matrix.example }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ${{ matrix.example }}
          production-branch: master
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "[Master] Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
          netlify-config-path: "./examples/${{ matrix.example }}/netlify.toml"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
