name: next Release

on:
  push:
    paths:
      - ".changeset/**"
      - "packages/**"
    branches:
      - next

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - name: Creating .npmrc
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies & Build
        run: |
          npm ci
          npm run bootstrap
      #- name: Lint
      #  run: npm run lint
      #- name: Test
      #  run: npm test
      - name: Copy changesets for Stable version
        run: cp -r ./.changeset/ ./_changeset/ 
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: npm run changeset version
          publish: npm run changeset publish -- --tag next
          commit: "ci(changesets): next version packages"
          title: "ci(changesets): next version packages"
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.PANKOD_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
