name: Lint Commit Messages
on: [pull_request]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #- uses: wagoid/commitlint-github-action@v4
      - uses: nick-fields/private-action-loader@v3
        if: ${{ 'pankod/refine' == github.repository }}
        with:
          pal-repo-name: refinedev/doc-change-check@v1.4
          pal-repo-token: ${{ secrets.PANKOD_BOT_TOKEN }}
          github-token: ${{ secrets.PANKOD_BOT_TOKEN }}