name: Pull Request Documentation [synchronize]

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
      - closed
    paths:
      - "documentation/**"
jobs:
  documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.PANKOD_BOT_TOKEN }}
          dist: build
          teardown: 'true'
          build: |
            cd documentation
            npm install
            npm run build
      - name: Send custom variable to Meercode Build
        uses: meercodeio/meercode-custom-variable@0.1.0
        with:
          meercode-token: ${{ secrets.MEERCODE_TOKEN }}
          url: '${{ steps.preview_step.outputs.preview_url }}'
      - uses: tzkhan/pr-update-action@v2
        with:
          repo-token: "${{ secrets.PANKOD_BOT_TOKEN }}"
          base-branch-regex: '[a-z\d-_.\\/]+'
          head-branch-regex: '[a-z\d-_.\\/]+'
          body-template: |
            [Documentation preview!](${{ steps.preview_step.outputs.preview_url }})
          body-update-action: 'suffix'