name: PR Checks
on: [pull_request]

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    name: Commitlint
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
  #lint:
  #  runs-on: ubuntu-latest
  #  name: Lint
  #  steps:
  #    - uses: actions/checkout@v1
  #    - name: lint
  #      run: |
  #        npm ci
  #        npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    name: Bootstrap and Test
    steps:
      - uses: actions/checkout@v1
      - name: Cache node_modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install & Bootstrap
        run: |
          npm ci
          npm run bootstrap:all
      - name: Test
        run: |
          npm run test:all --skip-nx-cache
